api:
  address: 0.0.0.0:8888
  maxRequestBodySize: 128*1024*1024

etcd:
  address: 127.0.0.1:2379

minio:
  endpoint: 172.29.22.103:9000
  accessKey: miniokey
  secretKey: miniokey
  useSSL: false
  videoBucketName: tiktok-videos
  coverBucketName: tiktok-video-covers
  avatarBucketName: tiktok-user-avatars
  backgroundBucketName: tiktok-user-backgrounds
  expireTime: 3600 # 临时链接过期秒数

mysql:
  source:
    username: root
    password: root
    host: localhost
    port: 3306
    dbname: tiktok
  replica:
    username: root
    password: root
    host: localhost
    port: 3308
    dbname: tiktok

redis:
  address: "localhost:6379"
  password: ""
  expireTime: 2 # minute 键过期时间
  syncTime: 1 # minute 同步MySQL时间，一定要小于过期时间
  favorDB: 0 # favor数据库
  commentDB: 1 # comment数据库

service:
  user:
    address: 127.0.0.1:9001
  video:
    address: 127.0.0.1:9002
    limit: 2 # 每次feed的视频数量
  favor:
    address: 127.0.0.1:9003
